version: '3'
services:
    app:
        container_name: app
        build: .
        volumes:
            - .:/opt/app
            - ./node_modules:/opt/app/node_modules
        restart: always
        entrypoint: npm run dev
        depends_on:
            - mongo
        ports:
            - 8080:8080
        env_file:
            - .env
    mongo:
        container_name: mongo
        image: mongo:latest
        restart: always
        ports:
            - 27017:27017
        command: mongod --storageEngine=wiredTiger
        volumes:
            - data:/data/db

volumes:
    data:
